package com.formsdirectinc.services.account;

public enum ProductTypeEnum {
    FORM,
    FORM_FULL_ACCESS,
    ILR,
    PRINT_AND_MAIL,
    BUNDLE,
    DVD,
    DOCUMENT_TRANSLATION,
    DOCUMENT_TRANSLATION_SE,
    DOCUMENT_TRANSLATION_SE_UPLOAD,
    FDR,
    EBOOK,
    CONSULTATION,
    CONSULTATION_UPLOAD,
    CONSULTATION_UPLOAD_APPLICATION
}
