package com.formsdirectinc.dao;

// Generated Aug 2, 2006 9:46:46 AM by Hibernate Tools 3.1.0.beta5


import java.util.Date;



/**
 * CustomerSignup generated by hbm2java
 */
public class CustomerSignup  implements java.io.Serializable {

    // Fields    

     private long id;
     private Integer version;
     private String emailId;
     private String firstName;
     private String lastName;
     private String middleName;
     private String telephone;
     private String birthCountry;
     private String residentState;
     private String residentCountry;
     private String password;
     private String birthDate;
     private Date signupDate;
     private Integer userType;
     private Integer userStatus;
     private Integer hintQuestion;
     private String hintAnswer;
     private Integer optOut;
     private Boolean universalOptOut;
     private String site;
     //To add first or signup product of customer.
     private String interestedProduct;
     private String signupIPAddress;
     private String language;
     private Phone signinphone = new Phone();
     // Telephone number for oneadmin and other purpose.
     private String telephoneCountryCode;
     private String telephoneCountryName;
     private String authId;
     private Boolean profileComplete;
     private Boolean isGuestUser;

    // Constructors
    /** default constructor */
    public CustomerSignup() {
    }

	/** minimal constructor */
    public CustomerSignup(long id, String emailId) {
        this.id = id;
        this.emailId = emailId;
    }
    /** full constructor */
    public CustomerSignup(long id, String emailId, String firstName, String lastName, String middleName, String telephone, String birthCountry, String residentState, String residentCountry, String password, String birthDate, Date signupDate, Integer userType, Integer userStatus, Integer hintQuestion, String hintAnswer, String site,String interestedProduct,String signupIPAddress,String language,String telephoneCountryCode, String telephoneCountryName, String authId, Boolean profileComplete, Boolean isGuestUser) {
       this.id = id;
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.middleName = middleName;
       this.telephone = telephone;
       this.birthCountry = birthCountry;
       this.residentState = residentState;
       this.residentCountry = residentCountry;
       this.password = password;
       this.birthDate = birthDate;
       this.signupDate = signupDate;
       this.userType = userType;
       this.userStatus = userStatus;
       this.hintQuestion = hintQuestion;
       this.hintAnswer = hintAnswer;
       this.site = site;
       this.interestedProduct = interestedProduct;
       this.signupIPAddress=signupIPAddress;
       this.language=language;
       this.telephoneCountryCode = telephoneCountryCode;
       this.telephoneCountryName = telephoneCountryName;
       this.authId = authId;
       this.profileComplete = profileComplete;
       this.isGuestUser = isGuestUser;

    }
    
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getBirthCountry() {
        return this.birthCountry;
    }
    
    public void setBirthCountry(String birthCountry) {
        this.birthCountry = birthCountry;
    }
    public String getResidentState() {
        return this.residentState;
    }
    
    public void setResidentState(String residentState) {
        this.residentState = residentState;
    }
    public String getResidentCountry() {
        return this.residentCountry;
    }
    
    public void setResidentCountry(String residentCountry) {
        this.residentCountry = residentCountry;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }
    public Date getSignupDate() {
        return this.signupDate;
    }
    
    public void setSignupDate(Date signupDate) {
        this.signupDate = signupDate;
    }

    public Integer getUserType() {
        return this.userType;
    }
    
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
    public Integer getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
    public Integer getHintQuestion() {
        return this.hintQuestion;
    }
    
    public void setHintQuestion(Integer hintQuestion) {
        this.hintQuestion = hintQuestion;
    }
    public String getHintAnswer() {
        return this.hintAnswer;
    }
    
    public void setHintAnswer(String hintAnswer) {
        this.hintAnswer = hintAnswer;
    }
    public Integer getOptOut() {
        return this.optOut;
    }
    
    public void setOptOut(Integer optOut) {
        this.optOut = optOut;
    }

    public Boolean getUniversalOptOut() {
        return universalOptOut;
    }

    public void setUniversalOptOut(Boolean universalOptOut) {
        this.universalOptOut = universalOptOut;
    }

    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public Phone getSigninPhone() {
	return this.signinphone;
    }

    public void setSigninPhone(Phone signinphone) {
       	this.signinphone = signinphone;
    }

    public String getInterestedProduct() {
	return this.interestedProduct;
    }

    public void setInterestedProduct(String interestedProduct) {
       	this.interestedProduct = interestedProduct;
    }
    
    public String getSignupIPAddress() {
	return this.signupIPAddress;
    }

    public void setSignupIPAddress(String signupIPAddress) {
       	this.signupIPAddress = signupIPAddress;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }


    public String getTelephoneCountryCode() {
        return this.telephoneCountryCode;
    }

    public void setTelephoneCountryCode(String telephoneCountryCode) {
        this.telephoneCountryCode = telephoneCountryCode;
    }

    public String getTelephoneCountryName() {
        return this.telephoneCountryName;
    }

    public void setTelephoneCountryName(String telephoneCountryName) {
        this.telephoneCountryName = telephoneCountryName;
    }

    public String getAuthId() {
        return authId;
    }

    public void setAuthId(String authId) {
        this.authId = authId;
    }

    public Boolean getProfileComplete() {
        return this.profileComplete != null ? this.profileComplete : true;
    }

    public void setProfileComplete(Boolean profileComplete) {
        this.profileComplete = profileComplete;
    }

    public Phone getFormatedPhone() {
      String phoneNo=getTelephone();
      if(!phoneNo.equals("null")){			
        String [] phoneArray=phoneNo.split("-");
        if(phoneArray.length == 4){
	   signinphone.setCountry(phoneArray[0]);
	   signinphone.setAreaCode(phoneArray[1]);
	   signinphone.setPhone1(phoneArray[2]);
	   signinphone.setPhone2(phoneArray[3]);
	}else if(phoneArray.length == 2){
	   signinphone.setCountry(phoneArray[0]);
           signinphone.setPhone3(phoneArray[1]);
        }
      }
       return this.signinphone;
    }

    public Boolean getIsGuestUser() {
        return isGuestUser;
    }

    public void setIsGuestUser(Boolean guestUser) {
        isGuestUser = guestUser;
    }

    @Override
    public String toString() {
        return "CustomerSignup{" +
                "id=" + id +
                ", version=" + version +
                ", emailId='" + emailId + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", middleName='" + middleName + '\'' +
                ", telephone='" + telephone + '\'' +
                ", birthCountry='" + birthCountry + '\'' +
                ", residentState='" + residentState + '\'' +
                ", residentCountry='" + residentCountry + '\'' +
                ", password='" + password + '\'' +
                ", birthDate='" + birthDate + '\'' +
                ", signupDate=" + signupDate +
                ", userType=" + userType +
                ", userStatus=" + userStatus +
                ", hintQuestion=" + hintQuestion +
                ", hintAnswer='" + hintAnswer + '\'' +
                ", optOut=" + optOut +
                ", universalOptOut=" + universalOptOut +
                ", site='" + site + '\'' +
                ", interestedProduct='" + interestedProduct + '\'' +
                ", signupIPAddress='" + signupIPAddress + '\'' +
                ", language='" + language + '\'' +
                ", signinphone=" + signinphone +
                ", telephoneCountryCode='" + telephoneCountryCode + '\'' +
                ", telephoneCountryName='" + telephoneCountryName + '\'' +
                ", authId='" + authId + '\'' +
                ", profileComplete=" + profileComplete +
                ", isGuestUser=" + isGuestUser +
                '}';
    }
}


